# Generated by Django 4.2.2 on 2023-06-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productBrandName', models.CharField(max_length=30)),
                ('productBrandModel', models.CharField(max_length=30)),
                ('productBrandCost', models.FloatField()),
            ],
        ),
    ]
